"""
189 grade 4 perimeter and operations/algebraic thinking questions (MD, OA).

ALREADY RUN -- these questions are live in Supabase. This file is kept as the
source of record for data that is already in the database.

There is no dry-run flag: running this uploads on sight, and running it again
would duplicate every question above for Jaden. Check the `questions` table
before re-running.
"""
import json, urllib.request, time

URL = "https://zvffmucghcrqackghhlf.supabase.co/rest/v1/questions"
KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2ZmZtdWNnaGNycWFja2doaGxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY3MjkyNTIsImV4cCI6MjA5MjMwNTI1Mn0.eJHX6LmInRdBd5nt9t_jBJwILGEQ6_SeN6ADorlsWic"

def upload_batch(batch, batch_num):
    data = json.dumps(batch).encode()
    req = urllib.request.Request(URL, data=data, method='POST')
    req.add_header('Content-Type', 'application/json')
    req.add_header('apikey', KEY)
    req.add_header('Authorization', f'Bearer {KEY}')
    req.add_header('Prefer', 'return=minimal')
    try:
        with urllib.request.urlopen(req) as r:
            print(f"  Batch {batch_num} ({len(batch)} questions): HTTP {r.status}")
            return len(batch)
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        print(f"  Batch {batch_num} ERROR {e.code}: {body}")
        return 0
    finally:
        time.sleep(0.3)

# ─── OA single-choice (52 questions) ───────────────────────────────────────
oa_single = [
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"Sam has 24 apples. He puts them equally into 4 bags. How many apples are in each bag?","options":["A 4","B 6","C 8","D 12"],"correct":["B"],"hint":"Divide the total apples by the number of bags.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"A store has 56 cans of soup. They sell 19 cans on Monday and 14 cans on Tuesday. How many cans are left?","options":["A 23","B 33","C 37","D 43"],"correct":["A"],"hint":"Subtract both amounts sold from the starting total.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"Maya has $10. She buys a book for $3 and a pencil for $1. How much money does she have left?","options":["A $4","B $5","C $6","D $7"],"correct":["C"],"hint":"Add what she spent, then subtract from $10.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"There are 3 shelves. Each shelf holds 8 books. How many books are there in all?","options":["A 11","B 16","C 24","D 32"],"correct":["C"],"hint":"Multiply the number of shelves by books per shelf.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"A class has 27 students. The teacher puts them into groups of 3. How many groups are there?","options":["A 7","B 8","C 9","D 10"],"correct":["C"],"hint":"Divide the total students by the group size.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"Jake has 15 stickers. He gives 4 to his sister and 3 to his brother. How many stickers does Jake have now?","options":["A 7","B 8","C 9","D 12"],"correct":["B"],"hint":"Subtract both amounts given away from 15.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"A bakery makes 6 dozen cookies. How many cookies is that in all?","options":["A 60","B 66","C 72","D 78"],"correct":["C"],"hint":"One dozen equals 12. Multiply 6 by 12.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"Lily reads 8 pages every day. How many pages will she read in 7 days?","options":["A 48","B 54","C 56","D 64"],"correct":["C"],"hint":"Multiply the pages per day by the number of days.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"There are 32 students going on a field trip. Each van holds 8 students. How many vans are needed?","options":["A 3","B 4","C 5","D 6"],"correct":["B"],"hint":"Divide the total students by the van capacity.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"Tom earns $5 each week doing chores. After 6 weeks, he buys a toy for $18. How much money does Tom have left?","options":["A $10","B $12","C $13","D $15"],"correct":["B"],"hint":"First multiply to find total earnings, then subtract the toy cost.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"A farmer has 45 eggs. He packs them into cartons of 6. How many full cartons can he make, and how many eggs are left over?","options":["A 7 cartons, 2 left over","B 7 cartons, 3 left over","C 8 cartons, 0 left over","D 8 cartons, 3 left over"],"correct":["B"],"hint":"Divide 45 by 6. The remainder is left over.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"School starts at 8:00 AM. Lunch is 3 hours and 30 minutes later. What time is lunch?","options":["A 11:00 AM","B 11:30 AM","C 12:00 PM","D 12:30 PM"],"correct":["B"],"hint":"Add 3 hours and 30 minutes to 8:00 AM.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"Ana has 3 quarters, 2 dimes, and 1 nickel. How much money does she have?","options":["A $0.95","B $1.00","C $1.05","D $1.10"],"correct":["B"],"hint":"25+25+25+10+10+5 = ?","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"A movie is 1 hour and 45 minutes long. It starts at 2:15 PM. What time does it end?","options":["A 3:45 PM","B 4:00 PM","C 4:15 PM","D 4:30 PM"],"correct":["B"],"hint":"Add 1 hour 45 minutes to 2:15 PM.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"Ben has 48 marbles. He gives half to his friend. Then he loses 6 more. How many does Ben have now?","options":["A 16","B 18","C 20","D 24"],"correct":["B"],"hint":"Find half of 48, then subtract 6.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"Rosa saves $4 each week. Her brother saves $6 each week. After 5 weeks, how much more money has her brother saved?","options":["A $8","B $10","C $12","D $14"],"correct":["B"],"hint":"Find the difference per week, then multiply by 5.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"Carlos buys 4 packs of trading cards. Each pack has 9 cards. He gives away 12 cards. How many cards does he have left?","options":["A 22","B 24","C 26","D 36"],"correct":["B"],"hint":"Multiply to find total, then subtract the given-away cards.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"There are 5 tables in the cafeteria. 6 students sit at each table. 3 more students join. How many students are there now?","options":["A 30","B 31","C 33","D 36"],"correct":["C"],"hint":"Multiply first, then add the extra students.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"Which operation should you use to find how many total stickers 7 friends have if each friend has 5 stickers?","options":["A Addition","B Subtraction","C Multiplication","D Division"],"correct":["C"],"hint":"When you have equal groups, you multiply.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"A store has 63 oranges. They pack them equally into 7 boxes. Which number sentence finds how many go in each box?","options":["A 63 + 7 = ?","B 63 - 7 = ?","C 63 x 7 = ?","D 63 / 7 = ?"],"correct":["D"],"hint":"Sharing equally means division.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"Mia runs 2 miles every morning. She ran for 9 days, then took a 3-day break. How many miles did she run?","options":["A 12","B 16","C 18","D 24"],"correct":["C"],"hint":"Only count the days she actually ran.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"A pizza is cut into 8 slices. If 3 friends share it equally, how many slices does each person get, and how many are left over?","options":["A 2 slices each, 1 left over","B 2 slices each, 2 left over","C 3 slices each, 0 left over","D 3 slices each, 1 left over"],"correct":["B"],"hint":"Divide 8 by 3 and find the remainder.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"Kevin has 72 cents. He buys a pencil for 35 cents. How much change does he get back from $1.00?","options":["A 28 cents","B 37 cents","C 63 cents","D 65 cents"],"correct":["A"],"hint":"Find what Kevin spends total, then subtract from 100 cents.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"In a box there are red, blue, and green crayons. There are 12 red, 8 blue, and 5 green. How many crayons are there in all?","options":["A 20","B 23","C 25","D 28"],"correct":["C"],"hint":"Add all three amounts together.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"Amy has 4 bags of 7 oranges each, and 3 loose oranges. How many oranges does she have in all?","options":["A 28","B 30","C 31","D 34"],"correct":["C"],"hint":"Multiply 4 x 7, then add the 3 loose oranges.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"A boy collects 9 shells each day for 6 days. He gives 15 to his mom. How many does he keep?","options":["A 30","B 36","C 39","D 54"],"correct":["C"],"hint":"First find total shells, then subtract the ones given away.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"Dan had some stickers. He got 14 more and now has 33. How many did he start with?","options":["A 17","B 18","C 19","D 20"],"correct":["C"],"hint":"Subtract the new stickers from the total to find the starting amount.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"Class A has 28 students and Class B has 22 students. They split into equal teams of 5. How many teams are there?","options":["A 8","B 9","C 10","D 12"],"correct":["C"],"hint":"First add both classes together, then divide by 5.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"A carton holds 12 eggs. A chef uses 2 whole cartons and 5 extra eggs. How many eggs does the chef use?","options":["A 24","B 26","C 28","D 29"],"correct":["D"],"hint":"Multiply 2 x 12, then add 5.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"Rachel has $20. She wants to buy 3 notebooks that cost $4 each. Does she have enough, and how much will be left?","options":["A Yes, $6 left","B Yes, $8 left","C No, she needs $2 more","D No, she needs $4 more"],"correct":["B"],"hint":"Find the total cost of 3 notebooks, then compare to $20.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"There are 40 students at a party. Half went home early. Then 7 more left. How many students remain?","options":["A 12","B 13","C 14","D 15"],"correct":["B"],"hint":"First halve 40, then subtract 7.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"Ella earns $7 per hour. She works 4 hours on Saturday and 3 hours on Sunday. How much does she earn in all?","options":["A $42","B $46","C $49","D $56"],"correct":["C"],"hint":"Add the hours for both days, then multiply by $7.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"Which is the best estimate for 47 + 38?","options":["A About 70","B About 80","C About 90","D About 100"],"correct":["C"],"hint":"Round each number to the nearest 10, then add.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"A bag has 35 grapes. Omar eats some grapes and has 18 left. How many grapes did Omar eat?","options":["A 13","B 15","C 17","D 18"],"correct":["C"],"hint":"Subtract the remaining grapes from the starting amount.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"A school store sells pencils for 25 cents each. Zara wants to buy 4 pencils. How much will they cost?","options":["A $0.75","B $0.90","C $1.00","D $1.25"],"correct":["C"],"hint":"Multiply 25 cents by 4.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"Leo planted 5 rows of flowers with 7 flowers in each row. Then 9 flowers wilted. How many healthy flowers are there?","options":["A 24","B 26","C 31","D 35"],"correct":["B"],"hint":"Multiply first to find total, then subtract wilted ones.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"Nadia has $15. She buys 2 items for $4.50 each. How much money does she have left?","options":["A $5.00","B $6.00","C $6.50","D $7.00"],"correct":["B"],"hint":"Find the total cost of 2 items, then subtract from $15.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"A train leaves at 9:20 AM and arrives at 11:05 AM. How long is the train ride?","options":["A 1 hour 35 minutes","B 1 hour 40 minutes","C 1 hour 45 minutes","D 2 hours"],"correct":["C"],"hint":"Count from 9:20 to 11:05.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"Ivan has 6 times as many baseball cards as his younger brother, who has 8 cards. How many cards does Ivan have?","options":["A 40","B 48","C 52","D 56"],"correct":["B"],"hint":"Multiply 6 by the number of cards the brother has.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"There are 50 chairs set up in 5 equal rows. How many chairs are in each row?","options":["A 8","B 9","C 10","D 11"],"correct":["C"],"hint":"Divide the total chairs by the number of rows.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"Paula scored 7 goals in each of 3 soccer games, and 5 goals in the 4th game. How many goals did she score in all?","options":["A 25","B 26","C 27","D 28"],"correct":["B"],"hint":"Multiply 7 x 3 for the first three games, then add 5.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"Kim has $1.00. She buys a granola bar for $0.65. How much change does she receive?","options":["A $0.25","B $0.30","C $0.35","D $0.40"],"correct":["C"],"hint":"Subtract the cost from $1.00.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"There are 81 students signed up for art club. They form groups of 9. How many groups are formed?","options":["A 7","B 8","C 9","D 10"],"correct":["C"],"hint":"Divide 81 by 9.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"A number is multiplied by 4 and then 10 is added. The result is 34. What is the number?","options":["A 4","B 5","C 6","D 7"],"correct":["C"],"hint":"Work backwards: subtract 10 from 34, then divide by 4.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"A toy costs $9. Ryan has $50. He buys as many toys as he can. How many toys can he buy and how much money is left?","options":["A 5 toys, $4 left","B 5 toys, $5 left","C 6 toys, $4 left","D 6 toys, $5 left"],"correct":["B"],"hint":"Divide $50 by $9. The remainder is money left over.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"A library has 120 books on 4 shelves. If each shelf has the same number of books, how many are on each shelf?","options":["A 25","B 28","C 30","D 32"],"correct":["C"],"hint":"Divide 120 by 4.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"Sophia baked 48 muffins. She sold them in bags of 4. How many bags did she fill?","options":["A 10","B 11","C 12","D 14"],"correct":["C"],"hint":"Divide 48 by 4.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"Mike had some money. He spent $12 and then earned $7. Now he has $20. How much did he start with?","options":["A $23","B $24","C $25","D $26"],"correct":["C"],"hint":"Work backwards: add $12, then subtract $7.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"In PE class, students run 3 laps around a 400-meter track. How many meters do they run in all?","options":["A 800 m","B 1000 m","C 1200 m","D 1400 m"],"correct":["C"],"hint":"Multiply 3 by 400.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"Mrs. Lee has 34 students. She gives each student 2 sheets of paper. How many sheets does she use?","options":["A 58","B 64","C 68","D 72"],"correct":["C"],"hint":"Multiply 34 by 2.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"Which number sentence is correct for: 'A jar has 36 candies. 4 children share them equally.'","options":["A 36 + 4 = 40","B 36 - 4 = 32","C 36 x 4 = 144","D 36 / 4 = 9"],"correct":["D"],"hint":"Sharing equally uses division.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"There are 30 students in a class. 12 are wearing hats. How many students are NOT wearing hats?","options":["A 12","B 16","C 18","D 20"],"correct":["C"],"hint":"Subtract 12 from 30.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"single","text":"A teacher buys 8 boxes of markers with 10 markers each. She gives out 35 markers. How many markers are left?","options":["A 40","B 45","C 50","D 55"],"correct":["B"],"hint":"Multiply 8 x 10 to find total, then subtract 35.","active":True},
]

# ─── OA numeric (46 questions) ──────────────────────────────────────────────
oa_numeric = [
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"There are 5 boxes. Each box has 9 crayons. How many crayons are there in total?","options":None,"correct":45,"hint":"Multiply 5 by 9.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"A farmer has 28 chickens. He buys 14 more. Then 6 chickens escape. How many chickens does he have now?","options":None,"correct":36,"hint":"Add 28 and 14, then subtract 6.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"A school collects 120 cans in 3 days, collecting the same number each day. How many cans are collected each day?","options":None,"correct":40,"hint":"Divide 120 by 3.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"Jasmine has 7 boxes of 8 pencils each. She uses 13 pencils. How many pencils does she have left?","options":None,"correct":43,"hint":"Find total pencils (7x8), then subtract 13.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"A pitcher holds 64 ounces of juice. If 8 children share it equally, how many ounces does each child get?","options":None,"correct":8,"hint":"Divide 64 by 8.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"Caleb scores 9 points in each of 6 rounds of a game. What is his total score?","options":None,"correct":54,"hint":"Multiply 9 by 6.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"A garden has 48 flowers in 6 equal rows. How many flowers are in each row?","options":None,"correct":8,"hint":"Divide 48 by 6.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"Diana reads 15 pages on Monday, 22 pages on Tuesday, and 18 pages on Wednesday. How many pages has she read in all?","options":None,"correct":55,"hint":"Add all three amounts: 15 + 22 + 18.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"A store has 90 balloons. They sell 35 on Friday and 28 on Saturday. How many balloons are left?","options":None,"correct":27,"hint":"Add the balloons sold on both days, then subtract from 90.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"Max has 3 times as many stamps as his sister. His sister has 11 stamps. How many stamps does Max have?","options":None,"correct":33,"hint":"Multiply 3 by 11.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"A restaurant serves 4 tables, each with 6 people. Each person orders 1 meal. How many meals are served?","options":None,"correct":24,"hint":"Multiply 4 by 6.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"Tina has $25. She buys a game for $16 and a book for $5. How much money does she have left?","options":None,"correct":4,"hint":"Add the prices of both items, then subtract from $25.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"There are 36 students. Each table can seat 4 students. How many tables are needed?","options":None,"correct":9,"hint":"Divide 36 by 4.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"Owen saves $3 each day for 9 days. How much money does he save in all?","options":None,"correct":27,"hint":"Multiply $3 by 9 days.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"There are 100 students on 4 teams. Teams A and B each have 28 students. Team C has 22 students. How many students are on Team D?","options":None,"correct":22,"hint":"Add up A, B, and C, then subtract from 100.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"A book has 200 pages. Grace reads 40 pages each day. How many days will it take her to finish the book?","options":None,"correct":5,"hint":"Divide 200 by 40.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"Victor has 64 toy cars. He keeps half and gives the other half to his cousins. How many cars does Victor keep?","options":None,"correct":32,"hint":"Divide 64 by 2.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"A school trip costs $8 per student. There are 7 students going. How much does the trip cost in total?","options":None,"correct":56,"hint":"Multiply $8 by 7.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"Ellie has 50 beads. She uses 8 beads to make one bracelet. How many full bracelets can she make?","options":None,"correct":6,"hint":"Divide 50 by 8. Only count full bracelets.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"A box holds 10 oranges. A store has 7 full boxes and 4 extra oranges. How many oranges does the store have?","options":None,"correct":74,"hint":"Multiply 7 x 10, then add 4.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"Jake rides his bike 6 miles every day. How many miles will he ride in 8 days?","options":None,"correct":48,"hint":"Multiply 6 by 8.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"Abby has 4 bags with 7 apples each. She also has 5 loose apples. How many apples does she have in all?","options":None,"correct":33,"hint":"Multiply 4 x 7, then add 5.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"63 students are split into teams of 7. How many teams are there?","options":None,"correct":9,"hint":"Divide 63 by 7.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"A child has 3 rolls of 10 stickers and 8 extra stickers. How many stickers in all?","options":None,"correct":38,"hint":"Multiply 3 x 10, then add 8.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"There are 55 students going on a field trip. Each bus holds 10 students. How many buses are needed?","options":None,"correct":6,"hint":"Divide 55 by 10. You need enough buses for everyone - round up!","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"A child saves $5 each week for 10 weeks. She then spends $18 on a gift. How much does she have left?","options":None,"correct":32,"hint":"Multiply $5 by 10, then subtract $18.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"A store sells 7 boxes of 6 donuts on Saturday and 5 boxes of 6 donuts on Sunday. How many donuts were sold in all?","options":None,"correct":72,"hint":"Add the boxes for both days (7+5), then multiply by 6.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"Nathan had 80 points in a game. He lost 25 points and then gained 40 more. What is his final score?","options":None,"correct":95,"hint":"Start at 80, subtract 25, then add 40.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"A zoo has 9 cages. Each cage holds 6 animals. How many animals does the zoo have in total?","options":None,"correct":54,"hint":"Multiply 9 by 6.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"Sam has 72 trading cards. He splits them into equal piles of 8. How many piles does he make?","options":None,"correct":9,"hint":"Divide 72 by 8.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"A store has 96 water bottles to pack in boxes of 12. How many full boxes are packed?","options":None,"correct":8,"hint":"Divide 96 by 12.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"Maria has 5 jars of 9 marbles each. She gives 12 marbles to her friend. How many marbles does Maria have left?","options":None,"correct":33,"hint":"Multiply 5 x 9, then subtract 12.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"Tyler practices piano for 20 minutes each day. How many minutes does he practice in 7 days?","options":None,"correct":140,"hint":"Multiply 20 by 7.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"A bus has 8 rows of seats. Each row has 4 seats. How many seats does the bus have in total?","options":None,"correct":32,"hint":"Multiply 8 by 4.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"Lisa finds 7 nests, each with 4 eggs. Then 6 eggs hatch. How many eggs have not hatched?","options":None,"correct":22,"hint":"Multiply 7 x 4 to find total eggs, then subtract 6.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"Anna has 5 packs of 8 crayons. She loses 11 crayons. How many crayons does she have left?","options":None,"correct":29,"hint":"Multiply 5 x 8, then subtract 11.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"There are 42 apples on a tree. Birds eat 9 of them. Then 17 more ripen. How many apples are on the tree now?","options":None,"correct":50,"hint":"Start with 42, subtract 9, then add 17.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"A classroom has 25 students. Each student brings in 4 canned goods for a food drive. How many canned goods are there in all?","options":None,"correct":100,"hint":"Multiply 25 by 4.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"Henry earns $6 per hour. He works 5 hours. He spends $14. How much does he have left?","options":None,"correct":16,"hint":"Multiply $6 x 5 to find earnings, then subtract $14.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"A library gets 7 boxes with 11 books each. They already had 23 books. How many books does the library have in all?","options":None,"correct":100,"hint":"Multiply 7 x 11 to find new books, then add 23.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"Chloe has 4 quarters, 3 dimes, and 2 pennies. How many cents does she have in all?","options":None,"correct":132,"hint":"4x25 + 3x10 + 2x1 = ?","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"A group of 49 kids lines up in rows of 7. How many rows are there?","options":None,"correct":7,"hint":"Divide 49 by 7.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"Jacob has 8 groups of 5 marbles and gives 16 away. How many marbles are left?","options":None,"correct":24,"hint":"Multiply 8 x 5, then subtract 16.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"Zoe has $50. She buys 3 books at $9 each and 1 journal for $5. How much money does she have left?","options":None,"correct":18,"hint":"Multiply 3 x $9, add $5 for the journal, then subtract from $50.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"A gym class has 24 students. They play a game in teams of 6. How many teams are formed?","options":None,"correct":4,"hint":"Divide 24 by 6.","active":True},
{"subject":"Math","domain":"OA","category":"Problem Solving","type":"numeric","text":"A package of 60 pencils is shared among 5 classrooms equally. How many pencils does each classroom get?","options":None,"correct":12,"hint":"Divide 60 by 5.","active":True},
]

# ─── MD numeric (46 questions) ──────────────────────────────────────────────
md_numeric = [
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A rectangle has a length of 8 cm and a width of 5 cm. What is its perimeter?","options":None,"correct":26,"hint":"Perimeter = 2 x (length + width).","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A square has sides of 7 inches each. What is the perimeter of the square?","options":None,"correct":28,"hint":"Perimeter of a square = 4 x side length.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A triangle has sides of 5 cm, 7 cm, and 9 cm. What is the perimeter?","options":None,"correct":21,"hint":"Add all three side lengths together.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A rectangle is 12 feet long and 4 feet wide. What is its perimeter?","options":None,"correct":32,"hint":"Perimeter = 2 x (length + width).","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A square garden has sides of 9 meters. What is the perimeter of the garden?","options":None,"correct":36,"hint":"Multiply the side length by 4.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A triangle has sides of 6 in, 6 in, and 10 in. What is the perimeter?","options":None,"correct":22,"hint":"Add all three sides: 6 + 6 + 10.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A rectangle has a length of 15 cm and a width of 6 cm. What is the perimeter?","options":None,"correct":42,"hint":"Perimeter = 2 x (15 + 6).","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A square has a perimeter of 20 inches. How long is each side?","options":None,"correct":5,"hint":"Divide the perimeter by 4 to find one side.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A shape has sides of 3 cm, 4 cm, 5 cm, and 6 cm. What is the perimeter?","options":None,"correct":18,"hint":"Add all four sides: 3 + 4 + 5 + 6.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A rectangle has a perimeter of 30 cm and a width of 5 cm. What is the length?","options":None,"correct":10,"hint":"30 = 2 x (length + 5). Solve for length.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"An equilateral triangle has each side equal to 8 cm. What is the perimeter?","options":None,"correct":24,"hint":"An equilateral triangle has 3 equal sides. Multiply 8 by 3.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A rectangle is 10 m long and 3 m wide. What is the perimeter?","options":None,"correct":26,"hint":"Perimeter = 2 x (10 + 3).","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A square has a side of 11 cm. What is the perimeter?","options":None,"correct":44,"hint":"Multiply 11 by 4.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A triangle has sides of 9 cm, 12 cm, and 15 cm. What is the perimeter?","options":None,"correct":36,"hint":"Add 9 + 12 + 15.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A pentagon (5 sides) has all sides equal to 6 feet. What is the perimeter?","options":None,"correct":30,"hint":"Multiply 6 by 5.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A rectangle has a length of 20 cm and a width of 8 cm. What is the perimeter?","options":None,"correct":56,"hint":"Perimeter = 2 x (20 + 8).","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A shape has 4 sides: 5 m, 7 m, 5 m, and 7 m. What is the perimeter?","options":None,"correct":24,"hint":"Add all four sides: 5 + 7 + 5 + 7.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A square has a perimeter of 36 cm. What is the length of each side?","options":None,"correct":9,"hint":"Divide 36 by 4.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A rectangle is 14 feet long and 7 feet wide. What is the perimeter?","options":None,"correct":42,"hint":"Perimeter = 2 x (14 + 7).","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"An irregular shape has sides of 2 cm, 4 cm, 6 cm, 3 cm, and 5 cm. What is the perimeter?","options":None,"correct":20,"hint":"Add all five sides together.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A square sandbox has a side length of 6 feet. What is the perimeter?","options":None,"correct":24,"hint":"Multiply 6 by 4.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A rectangle has a width of 9 cm and a length of 13 cm. What is the perimeter?","options":None,"correct":44,"hint":"Perimeter = 2 x (13 + 9).","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A triangle has two sides each 7 cm long and one side 10 cm long. What is the perimeter?","options":None,"correct":24,"hint":"Add 7 + 7 + 10.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A regular hexagon (6 equal sides) has each side equal to 5 cm. What is the perimeter?","options":None,"correct":30,"hint":"Multiply 5 by 6.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A rectangle is 16 m long and 4 m wide. What is the perimeter?","options":None,"correct":40,"hint":"Perimeter = 2 x (16 + 4).","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A shape has sides 8, 8, 8, and 8 cm. What is the perimeter?","options":None,"correct":32,"hint":"All sides are equal. Multiply 8 by 4.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A rectangle has a length of 7 inches and a width of 3 inches. What is the perimeter?","options":None,"correct":20,"hint":"Perimeter = 2 x (7 + 3).","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A fence goes around a square yard. Each side is 15 feet. How much fencing is needed?","options":None,"correct":60,"hint":"Perimeter of a square = 4 x side.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A triangle has sides 11 cm, 8 cm, and 6 cm. What is the perimeter?","options":None,"correct":25,"hint":"Add all three sides: 11 + 8 + 6.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A rectangle is 18 cm long and 5 cm wide. What is the perimeter?","options":None,"correct":46,"hint":"Perimeter = 2 x (18 + 5).","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A shape has sides of 10 cm, 6 cm, 10 cm, and 6 cm. What is the perimeter?","options":None,"correct":32,"hint":"Add all four sides: 10 + 6 + 10 + 6.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A square has a side length of 13 cm. What is the perimeter?","options":None,"correct":52,"hint":"Multiply 13 by 4.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"An irregular shape has sides of 7, 3, 5, 4, and 6 cm. What is the perimeter?","options":None,"correct":25,"hint":"Add all five sides: 7 + 3 + 5 + 4 + 6.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A rectangle has a perimeter of 40 m. Its length is 12 m. What is the width?","options":None,"correct":8,"hint":"40 = 2 x (12 + width). Solve for width.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A square picture frame has a perimeter of 48 cm. How long is each side?","options":None,"correct":12,"hint":"Divide the perimeter by 4.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A shape has 6 sides, all equal to 4 cm. What is the perimeter?","options":None,"correct":24,"hint":"Multiply 4 by 6.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A rectangle is 22 cm long and 3 cm wide. What is the perimeter?","options":None,"correct":50,"hint":"Perimeter = 2 x (22 + 3).","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A triangle has all three sides equal to 12 cm. What is the perimeter?","options":None,"correct":36,"hint":"Multiply 12 by 3.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A rectangle has a length of 25 cm and a width of 10 cm. What is the perimeter?","options":None,"correct":70,"hint":"Perimeter = 2 x (25 + 10).","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A regular pentagon has all sides equal to 9 cm. What is the perimeter?","options":None,"correct":45,"hint":"Multiply 9 by 5.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A rectangle is 6 cm long and 6 cm wide. What is the perimeter?","options":None,"correct":24,"hint":"Perimeter = 2 x (6 + 6).","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A school hallway is shaped like a rectangle: 30 m long and 8 m wide. What is the perimeter?","options":None,"correct":76,"hint":"Perimeter = 2 x (30 + 8).","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A shape has sides of 4 cm, 9 cm, 4 cm, and 9 cm. What is the perimeter?","options":None,"correct":26,"hint":"Add all four sides: 4 + 9 + 4 + 9.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A square has a perimeter of 64 cm. What is the side length?","options":None,"correct":16,"hint":"Divide 64 by 4.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A park is shaped like a rectangle 50 m long and 20 m wide. What is the perimeter of the park?","options":None,"correct":140,"hint":"Perimeter = 2 x (50 + 20).","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A triangle has sides of 14 cm, 14 cm, and 10 cm. What is the perimeter?","options":None,"correct":38,"hint":"Add 14 + 14 + 10.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"numeric","text":"A rectangle has a perimeter of 50 cm and a length of 15 cm. What is the width?","options":None,"correct":10,"hint":"50 = 2 x (15 + width). Solve for width.","active":True},
]

# ─── MD single-choice (42 questions) ────────────────────────────────────────
md_single = [
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"Which formula finds the perimeter of a rectangle?","options":["A P = length x width","B P = 2 x (length + width)","C P = length + width","D P = 4 x side"],"correct":["B"],"hint":"Remember, you add the length and width, then double it.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"A rectangle is 6 cm long and 3 cm wide. What is the perimeter?","options":["A 9 cm","B 12 cm","C 18 cm","D 24 cm"],"correct":["C"],"hint":"Perimeter = 2 x (6 + 3).","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"A square has a side of 5 cm. What is the perimeter?","options":["A 10 cm","B 15 cm","C 20 cm","D 25 cm"],"correct":["C"],"hint":"Perimeter of a square = 4 x side.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"A triangle has sides 4 cm, 6 cm, and 8 cm. What is the perimeter?","options":["A 16 cm","B 18 cm","C 20 cm","D 22 cm"],"correct":["B"],"hint":"Add all three sides: 4 + 6 + 8.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"What is the perimeter of a square with side 10 m?","options":["A 20 m","B 30 m","C 40 m","D 100 m"],"correct":["C"],"hint":"Multiply the side by 4.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"Which shape has a perimeter found by adding all side lengths?","options":["A Only squares","B Only triangles","C Only rectangles","D All polygons"],"correct":["D"],"hint":"Perimeter means the total distance around any shape.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"A rectangle has a perimeter of 24 cm. Its length is 8 cm. What is the width?","options":["A 3 cm","B 4 cm","C 5 cm","D 6 cm"],"correct":["B"],"hint":"24 = 2 x (8 + width). Solve for width.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"Which rectangle has a perimeter of 28 cm?","options":["A Length 9 cm, Width 5 cm","B Length 10 cm, Width 4 cm","C Length 8 cm, Width 6 cm","D Length 12 cm, Width 2 cm"],"correct":["C"],"hint":"Try 2 x (L + W) for each option.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"Jake runs around a square park. Each side is 100 meters. How far does he run in one lap?","options":["A 200 m","B 300 m","C 400 m","D 500 m"],"correct":["C"],"hint":"The perimeter of a square is 4 x side.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"A triangle has all sides equal to 9 cm. What is the perimeter?","options":["A 18 cm","B 24 cm","C 27 cm","D 36 cm"],"correct":["C"],"hint":"Multiply 9 by 3.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"A rectangle has length 13 cm and width 5 cm. What is the perimeter?","options":["A 32 cm","B 36 cm","C 38 cm","D 40 cm"],"correct":["B"],"hint":"Perimeter = 2 x (13 + 5).","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"Which measurement unit is used for perimeter?","options":["A Square centimeters","B Centimeters","C Cubic centimeters","D No unit needed"],"correct":["B"],"hint":"Perimeter is a length, so it uses length units like cm or m.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"What is the perimeter of a rectangle with length 11 cm and width 7 cm?","options":["A 29 cm","B 32 cm","C 36 cm","D 38 cm"],"correct":["C"],"hint":"Perimeter = 2 x (11 + 7).","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"A garden is 9 m long and 4 m wide. How much fencing is needed to go all the way around?","options":["A 22 m","B 24 m","C 26 m","D 28 m"],"correct":["C"],"hint":"Perimeter = 2 x (9 + 4).","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"A square has a perimeter of 32 cm. What is the side length?","options":["A 6 cm","B 7 cm","C 8 cm","D 9 cm"],"correct":["C"],"hint":"Divide the perimeter by 4.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"A shape has 4 sides: 10 cm, 5 cm, 10 cm, and 5 cm. What is the perimeter?","options":["A 25 cm","B 28 cm","C 30 cm","D 32 cm"],"correct":["C"],"hint":"Add all four sides: 10 + 5 + 10 + 5.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"A rectangle has a perimeter of 44 cm and a width of 6 cm. What is the length?","options":["A 14 cm","B 16 cm","C 18 cm","D 20 cm"],"correct":["B"],"hint":"44 = 2 x (length + 6). Solve for length.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"Tom wants to put a border around a bulletin board that is 8 feet long and 5 feet wide. How much border does he need?","options":["A 22 ft","B 24 ft","C 26 ft","D 28 ft"],"correct":["C"],"hint":"Perimeter = 2 x (8 + 5).","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"A triangle has sides of 5, 12, and 13 cm. What is the perimeter?","options":["A 28 cm","B 29 cm","C 30 cm","D 31 cm"],"correct":["C"],"hint":"Add 5 + 12 + 13.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"What is the perimeter of a square with side 12 cm?","options":["A 36 cm","B 44 cm","C 48 cm","D 52 cm"],"correct":["C"],"hint":"Multiply 12 by 4.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"A rectangle is 4 times as long as it is wide. The width is 3 cm. What is the perimeter?","options":["A 24 cm","B 28 cm","C 30 cm","D 36 cm"],"correct":["C"],"hint":"Find the length (4 x 3), then use P = 2 x (L + W).","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"A rectangular pool is 25 m long and 10 m wide. What is the perimeter?","options":["A 60 m","B 65 m","C 70 m","D 75 m"],"correct":["C"],"hint":"Perimeter = 2 x (25 + 10).","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"Rectangle A is 8x4 cm and Rectangle B is 6x6 cm. Which has the greater perimeter?","options":["A Rectangle A","B Rectangle B","C They are equal (both 24 cm)","D Not enough information"],"correct":["C"],"hint":"Calculate 2x(8+4) and 2x(6+6) and compare.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"A rectangle has a perimeter of 60 m and a length of 20 m. What is the width?","options":["A 8 m","B 10 m","C 12 m","D 15 m"],"correct":["B"],"hint":"60 = 2 x (20 + width). Solve for width.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"A rectangular rug is 7 feet long and 5 feet wide. What is the perimeter of the rug?","options":["A 22 ft","B 24 ft","C 25 ft","D 28 ft"],"correct":["A"],"hint":"Perimeter = 2 x (7 + 5).","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"A shape has 4 sides: 3 cm, 7 cm, 3 cm, and 7 cm. What is the perimeter?","options":["A 17 cm","B 18 cm","C 20 cm","D 22 cm"],"correct":["C"],"hint":"Add all four sides: 3 + 7 + 3 + 7.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"A square table has a side of 3 feet. What is the perimeter of the table?","options":["A 9 ft","B 10 ft","C 12 ft","D 15 ft"],"correct":["C"],"hint":"Perimeter of a square = 4 x side.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"A rectangle has length 17 cm and width 9 cm. What is the perimeter?","options":["A 48 cm","B 50 cm","C 52 cm","D 54 cm"],"correct":["C"],"hint":"Perimeter = 2 x (17 + 9).","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"A swimming pool has a perimeter of 80 m. It is 25 m long. How wide is the pool?","options":["A 12 m","B 14 m","C 15 m","D 16 m"],"correct":["C"],"hint":"80 = 2 x (25 + width). Solve for width.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"A triangle has two sides of 8 cm and one side of 6 cm. What is the perimeter?","options":["A 20 cm","B 22 cm","C 24 cm","D 26 cm"],"correct":["B"],"hint":"Add 8 + 8 + 6.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"A regular pentagon has 5 equal sides of 4 cm each. What is the perimeter?","options":["A 16 cm","B 18 cm","C 20 cm","D 24 cm"],"correct":["C"],"hint":"Multiply 4 by 5.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"Lisa is putting a fence around her rectangular garden: 12 m long and 8 m wide. How much fence does she need?","options":["A 36 m","B 38 m","C 40 m","D 42 m"],"correct":["C"],"hint":"Perimeter = 2 x (12 + 8).","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"A rectangle is 20 cm long and 9 cm wide. What is the perimeter?","options":["A 50 cm","B 54 cm","C 58 cm","D 62 cm"],"correct":["C"],"hint":"Perimeter = 2 x (20 + 9).","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"A square has a perimeter of 52 cm. What is its side length?","options":["A 11 cm","B 12 cm","C 13 cm","D 14 cm"],"correct":["C"],"hint":"Divide 52 by 4.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"An irregular quadrilateral has sides 8, 5, 9, and 6 cm. What is the perimeter?","options":["A 25 cm","B 26 cm","C 27 cm","D 28 cm"],"correct":["D"],"hint":"Add all four sides: 8 + 5 + 9 + 6.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"A rectangle has a perimeter of 56 cm and a width of 8 cm. What is the length?","options":["A 18 cm","B 20 cm","C 22 cm","D 24 cm"],"correct":["B"],"hint":"56 = 2 x (length + 8). Solve for length.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"Which rectangle has the greatest perimeter? (each given as length x width)","options":["A 7 x 4","B 10 x 2","C 6 x 5","D 8 x 3"],"correct":["C"],"hint":"Calculate 2x(L+W) for each and compare.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"A rectangle is 3 times as long as it is wide. The width is 4 cm. What is the perimeter?","options":["A 28 cm","B 30 cm","C 32 cm","D 36 cm"],"correct":["C"],"hint":"Length = 3 x 4 = 12. Then P = 2 x (12 + 4).","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"A rectangular path goes around a playground that is 40 m long and 25 m wide. How long is the path?","options":["A 110 m","B 120 m","C 130 m","D 140 m"],"correct":["C"],"hint":"Perimeter = 2 x (40 + 25).","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"A square has a perimeter of 80 cm. What is its side length?","options":["A 16 cm","B 18 cm","C 20 cm","D 22 cm"],"correct":["C"],"hint":"Divide 80 by 4.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"A shape has sides 15, 20, 15, and 20 cm. What is the perimeter?","options":["A 60 cm","B 65 cm","C 70 cm","D 75 cm"],"correct":["C"],"hint":"Add all four sides: 15 + 20 + 15 + 20.","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"A rectangle has a length of 30 cm and a width of 15 cm. What is the perimeter?","options":["A 80 cm","B 85 cm","C 90 cm","D 95 cm"],"correct":["C"],"hint":"Perimeter = 2 x (30 + 15).","active":True},
{"subject":"Math","domain":"MD","category":"Perimeter","type":"single","text":"A room is rectangular: 5 m wide and 8 m long. What is the perimeter?","options":["A 24 m","B 26 m","C 28 m","D 30 m"],"correct":["B"],"hint":"Perimeter = 2 x (5 + 8).","active":True},
]

# Summary
print(f"OA single: {len(oa_single)}, OA numeric: {len(oa_numeric)}, Total OA new: {len(oa_single)+len(oa_numeric)}")
print(f"MD numeric: {len(md_numeric)}, MD single: {len(md_single)}, Total MD new: {len(md_numeric)+len(md_single)}")

# ─── Upload ──────────────────────────────────────────────────────────────────
total_uploaded = 0

def upload_all(questions, label):
    global total_uploaded
    single_qs = [q for q in questions if q['type'] == 'single']
    numeric_qs = [q for q in questions if q['type'] == 'numeric']
    print(f"\n=== Uploading {label}: {len(single_qs)} single + {len(numeric_qs)} numeric ===")
    batch_num = 0
    for qs in [single_qs, numeric_qs]:
        for i in range(0, len(qs), 25):
            batch_num += 1
            total_uploaded += upload_batch(qs[i:i+25], batch_num)

upload_all(oa_single + oa_numeric, "Problem Solving (OA)")
upload_all(md_numeric + md_single, "Perimeter (MD)")

print(f"\n=== DONE: {total_uploaded} questions uploaded total ===")
