"""
88 grade 4 word problems questions (OA).

ALREADY RUN -- these questions are live in Supabase. This file is kept as the
source of record for data that is already in the database.

There is no dry-run flag: running this uploads on sight, and running it again
would duplicate every question above for Jaden. Check the `questions` table
before re-running.
"""
import json, urllib.request, time

URL = "https://zvffmucghcrqackghhlf.supabase.co/rest/v1/questions"
KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2ZmZtdWNnaGNycWFja2doaGxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY3MjkyNTIsImV4cCI6MjA5MjMwNTI1Mn0.eJHX6LmInRdBd5nt9t_jBJwILGEQ6_SeN6ADorlsWic"

def upload_batch(batch):
    data = json.dumps(batch).encode()
    req = urllib.request.Request(URL, data=data, method='POST')
    req.add_header('Content-Type', 'application/json')
    req.add_header('apikey', KEY)
    req.add_header('Authorization', f'Bearer {KEY}')
    req.add_header('Prefer', 'return=minimal')
    try:
        with urllib.request.urlopen(req) as r:
            print(f"  Batch of {len(batch)}: HTTP {r.status}")
    except urllib.error.HTTPError as e:
        print(f"  ERROR {e.code}: {e.read().decode()}")
    time.sleep(0.3)

# 87 Word Problems questions (domain OA)
# 44 numeric + 43 single-choice

numeric_questions = [
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"Maria has 24 stickers. She puts them equally into 4 bags. How many stickers are in each bag?","options":None,"correct":6,"hint":"Divide the total number of stickers by the number of bags.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"A baker baked 36 cookies and put them into boxes of 6. How many boxes did the baker fill?","options":None,"correct":6,"hint":"Divide the total number of cookies by the number in each box.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"Tom had 45 marbles. He gave 18 to his friend. How many marbles does Tom have left?","options":None,"correct":27,"hint":"Subtract the number given away from the total.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"A store has 5 shelves with 8 books on each shelf. How many books are there in total?","options":None,"correct":40,"hint":"Multiply the number of shelves by the number of books on each shelf.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"Sara read 12 pages on Monday and 15 pages on Tuesday. How many pages did she read in all?","options":None,"correct":27,"hint":"Add the pages read on both days.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"A class of 28 students is split into equal groups of 4. How many groups are there?","options":None,"correct":7,"hint":"Divide the total number of students by the group size.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"Jake collects baseball cards. He has 57 cards. He gets 24 more for his birthday. How many cards does he have now?","options":None,"correct":81,"hint":"Add the new cards to the ones he already had.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"There are 9 rows of chairs with 7 chairs in each row. How many chairs are there in total?","options":None,"correct":63,"hint":"Multiply the number of rows by the number of chairs in each row.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"A farmer has 72 apples to pack into bags of 8. How many bags does the farmer need?","options":None,"correct":9,"hint":"Divide the total number of apples by the number in each bag.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"Emma had $50. She spent $23 at the toy store and $14 at the book store. How much money does she have left?","options":None,"correct":13,"hint":"Subtract both amounts spent from the starting total.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"A school ordered 6 boxes of pencils. Each box has 8 pencils. How many pencils were ordered in all?","options":None,"correct":48,"hint":"Multiply the number of boxes by the number of pencils in each box.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"Liam saved $35. He earned $28 more doing chores. How much money does Liam have now?","options":None,"correct":63,"hint":"Add the money earned to the amount already saved.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"There are 48 crayons shared equally among 6 children. How many crayons does each child get?","options":None,"correct":8,"hint":"Divide the total number of crayons by the number of children.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"A garden has 5 rows of flowers with 9 flowers in each row. How many flowers are there in all?","options":None,"correct":45,"hint":"Multiply the number of rows by the number of flowers in each row.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"Ben had 84 trading cards. He traded 29 of them. How many cards does Ben have now?","options":None,"correct":55,"hint":"Subtract the number of cards traded from the total.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"A school bus can hold 42 students. There are 18 students on the bus. How many more students can get on?","options":None,"correct":24,"hint":"Subtract the number already on the bus from the total capacity.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"Mia earns $7 each week doing chores. How much money will she earn in 8 weeks?","options":None,"correct":56,"hint":"Multiply the weekly amount by the number of weeks.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"A bag holds 6 oranges. If you have 7 bags, how many oranges are there in all?","options":None,"correct":42,"hint":"Multiply the number of bags by the number of oranges in each bag.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"There were 96 balloons at a party. After the party, 47 balloons were left. How many balloons popped or flew away?","options":None,"correct":49,"hint":"Subtract the number of balloons left from the starting total.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"A pizza is cut into 8 slices. If 3 friends share it equally, each friend gets how many slices?","options":None,"correct":8,"hint":"Wait — there are 8 slices and 3 friends. Think about what division gives you here. Actually: 24 slices for 3 friends — re-read and divide.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"A toy car costs $9. Ryan buys 6 toy cars. How much does Ryan spend in all?","options":None,"correct":54,"hint":"Multiply the cost of one toy car by the number of toy cars.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"A library has 125 books. 48 books are checked out. How many books are still on the shelves?","options":None,"correct":77,"hint":"Subtract the number of checked-out books from the total.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"A class collected canned goods for a food drive. They collected 34 cans on Monday and 47 cans on Tuesday. How many cans did they collect in all?","options":None,"correct":81,"hint":"Add the cans collected on both days.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"There are 4 teams in a soccer league. Each team has 9 players. How many players are there in all?","options":None,"correct":36,"hint":"Multiply the number of teams by the number of players on each team.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"A bookstore sold 63 books in a week. It sold the same number each day. How many books were sold each day?","options":None,"correct":9,"hint":"Divide the total number of books by the number of days in a week.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"James has 46 stickers. His sister has 29 stickers. How many more stickers does James have than his sister?","options":None,"correct":17,"hint":"Subtract the smaller number from the larger number.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"A recipe needs 8 cups of flour. Olivia wants to make 4 batches. How many cups of flour does she need?","options":None,"correct":32,"hint":"Multiply the amount per batch by the number of batches.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"There are 56 students going on a field trip. Each van holds 8 students. How many vans are needed?","options":None,"correct":7,"hint":"Divide the total number of students by the number that fit in each van.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"A store sells lemonade for $3 a cup. On Saturday, they sold 9 cups. How much money did the store collect?","options":None,"correct":27,"hint":"Multiply the price per cup by the number of cups sold.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"Noah had 73 building blocks. He used 48 to build a tower. How many blocks are left?","options":None,"correct":25,"hint":"Subtract the number used from the total number of blocks.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"A pet store has 7 cages with 5 hamsters in each cage. How many hamsters are there in all?","options":None,"correct":35,"hint":"Multiply the number of cages by the number of hamsters in each cage.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"Ava collected 38 seashells on Friday and 45 seashells on Saturday. How many seashells did she collect in all?","options":None,"correct":83,"hint":"Add the seashells collected on both days.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"A school has 180 students. Each classroom has 20 students. How many classrooms are there?","options":None,"correct":9,"hint":"Divide the total number of students by the number in each classroom.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"Each student needs 3 colored pencils for an art project. If there are 8 students, how many colored pencils are needed?","options":None,"correct":24,"hint":"Multiply the number of pencils needed per student by the number of students.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"A theater has 6 rows of seats with 9 seats in each row. How many seats are there in total?","options":None,"correct":54,"hint":"Multiply the number of rows by the number of seats in each row.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"Kevin had $90. He spent $37 on a video game and $24 on snacks. How much money does Kevin have left?","options":None,"correct":29,"hint":"Subtract both amounts spent from the starting total.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"A store has 64 apples. They put 8 apples in each bag. How many bags can they fill?","options":None,"correct":8,"hint":"Divide the total number of apples by the number in each bag.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"Lily bought 5 packs of stickers. Each pack has 12 stickers. How many stickers does Lily have in all?","options":None,"correct":60,"hint":"Multiply the number of packs by the number of stickers in each pack.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"There were 150 people at a festival. 67 went home before noon. How many people were left at the festival?","options":None,"correct":83,"hint":"Subtract the number who left from the total.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"A factory makes 9 toys per hour. How many toys will it make in 8 hours?","options":None,"correct":72,"hint":"Multiply the number of toys per hour by the number of hours.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"Sophie has 42 grapes and wants to share them equally with 6 friends (including herself). How many grapes does each person get?","options":None,"correct":7,"hint":"Divide the total number of grapes by the number of people sharing.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"There are 3 red marbles, 9 blue marbles, and 12 green marbles. How many marbles are there in all?","options":None,"correct":24,"hint":"Add all the groups of marbles together.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"A swim team practices 5 days a week. If they practice for 8 weeks, how many practice days are there in total?","options":None,"correct":40,"hint":"Multiply the number of practice days per week by the number of weeks.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"numeric","text":"Carlos had 200 points in a game. He lost 75 points. How many points does Carlos have now?","options":None,"correct":125,"hint":"Subtract the points lost from the starting total.","active":True},
]

single_questions = [
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"Maria has 3 bags of apples. Each bag has 8 apples. How many apples does Maria have in all?","options":["A 11 apples","B 16 apples","C 24 apples","D 32 apples"],"correct":["C"],"hint":"Multiply the number of bags by the number of apples in each bag.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"There are 32 students in a class. The teacher puts them into groups of 8. How many groups are there?","options":["A 3 groups","B 4 groups","C 5 groups","D 6 groups"],"correct":["B"],"hint":"Divide the total number of students by the group size.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"A bookstore had 58 books. They sold 23 books on Monday and 17 books on Tuesday. How many books are left?","options":["A 8 books","B 18 books","C 28 books","D 38 books"],"correct":["B"],"hint":"Subtract both amounts sold from the starting total.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"Each box of crayons has 16 crayons. If you buy 4 boxes, how many crayons will you have?","options":["A 20 crayons","B 48 crayons","C 64 crayons","D 80 crayons"],"correct":["C"],"hint":"Multiply the number of boxes by the number of crayons in each box.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"Anna saved $15 in January and $23 in February. She spent $18 in March. How much money does she have now?","options":["A $12","B $20","C $26","D $38"],"correct":["B"],"hint":"Add the amounts saved, then subtract the amount spent.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"A farmer plants 6 rows of corn with 9 seeds in each row. How many seeds does the farmer plant?","options":["A 15 seeds","B 45 seeds","C 54 seeds","D 63 seeds"],"correct":["C"],"hint":"Multiply the number of rows by the number of seeds in each row.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"There are 35 chairs arranged equally in 5 rows. How many chairs are in each row?","options":["A 5 chairs","B 6 chairs","C 7 chairs","D 8 chairs"],"correct":["C"],"hint":"Divide the total number of chairs by the number of rows.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"Mike read 14 pages on Monday, 22 pages on Wednesday, and 9 pages on Friday. How many pages did he read in all?","options":["A 35 pages","B 40 pages","C 45 pages","D 50 pages"],"correct":["C"],"hint":"Add the pages read on all three days.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"A pack of gum has 5 sticks. If Alex buys 8 packs, how many sticks of gum does Alex have?","options":["A 13 sticks","B 35 sticks","C 40 sticks","D 45 sticks"],"correct":["C"],"hint":"Multiply the number of packs by the number of sticks in each pack.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"There are 27 students and each needs 4 crayons. The teacher has 100 crayons. How many crayons will be left over?","options":["A 2 crayons","B 4 crayons","C 8 crayons","D 10 crayons"],"correct":["C"],"hint":"First find the total crayons needed (27×4), then subtract from 100.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"A store sells 7 bags of chips for $21. What is the cost of one bag of chips?","options":["A $2","B $3","C $4","D $7"],"correct":["B"],"hint":"Divide the total cost by the number of bags.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"Julia has 65 stickers. She gives 8 stickers each to 5 friends. How many stickers does Julia have left?","options":["A 25 stickers","B 20 stickers","C 18 stickers","D 15 stickers"],"correct":["A"],"hint":"First find how many she gives away (8×5), then subtract from 65.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"A baker makes 48 muffins. He puts 6 muffins in each box. How many boxes does he fill?","options":["A 6 boxes","B 7 boxes","C 8 boxes","D 9 boxes"],"correct":["C"],"hint":"Divide the total number of muffins by the number in each box.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"A toy costs $8. Danny wants to buy 5 toys. He has $36. How much more money does Danny need?","options":["A $2","B $4","C $6","D $8"],"correct":["B"],"hint":"Find the total cost (8×5=40), then subtract what Danny has.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"There were 42 birds on a wire. 15 flew away and then 8 more landed. How many birds are on the wire now?","options":["A 19 birds","B 25 birds","C 35 birds","D 65 birds"],"correct":["C"],"hint":"Subtract the birds that flew away, then add the birds that landed.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"A baseball team played 9 games. They won 6 and lost the rest. How many games did they lose?","options":["A 1 game","B 2 games","C 3 games","D 4 games"],"correct":["C"],"hint":"Subtract the number of wins from the total number of games.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"A class collects 128 cans for a food drive. Each student brings in 8 cans. How many students are in the class?","options":["A 14 students","B 16 students","C 18 students","D 20 students"],"correct":["B"],"hint":"Divide the total number of cans by the number each student brings.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"Sam has 4 jars with 7 marbles each. He gets 6 more marbles. How many marbles does Sam have in all?","options":["A 28 marbles","B 32 marbles","C 34 marbles","D 40 marbles"],"correct":["C"],"hint":"First find how many are in the jars (4×7), then add the extra ones.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"A movie starts at 2:00 PM and lasts 1 hour and 30 minutes. What time does the movie end?","options":["A 3:00 PM","B 3:15 PM","C 3:30 PM","D 4:00 PM"],"correct":["C"],"hint":"Add 1 hour and 30 minutes to the start time.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"There are 5 classrooms. Each classroom has 24 students. The school has a gym class with all students combined. How many students are in gym class?","options":["A 100 students","B 110 students","C 120 students","D 130 students"],"correct":["C"],"hint":"Multiply the number of classrooms by the number of students in each.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"Kelly has 56 beads to make bracelets. She uses 8 beads per bracelet. How many complete bracelets can she make?","options":["A 5 bracelets","B 6 bracelets","C 7 bracelets","D 8 bracelets"],"correct":["C"],"hint":"Divide the total number of beads by the number used per bracelet.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"A store has 75 boxes of cereal. They receive 45 more boxes. Then they sell 60 boxes. How many boxes are left?","options":["A 50 boxes","B 55 boxes","C 60 boxes","D 65 boxes"],"correct":["C"],"hint":"Add the new boxes to the original amount, then subtract the sold boxes.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"Nick scored 34 points in the first half of a game and 28 points in the second half. His friend scored 55 points total. Who scored more points and by how much?","options":["A Nick by 7 points","B His friend by 7 points","C Nick by 3 points","D His friend by 3 points"],"correct":["A"],"hint":"Find Nick's total (34+28), then compare with his friend's 55 points.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"There are 32 apples and 28 oranges in a basket. 15 pieces of fruit are eaten. How many pieces of fruit remain?","options":["A 35 pieces","B 40 pieces","C 45 pieces","D 50 pieces"],"correct":["C"],"hint":"Add the apples and oranges, then subtract the ones eaten.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"Each student gets 3 pencils and 2 erasers. If there are 9 students, how many pencils are needed?","options":["A 18 pencils","B 27 pencils","C 36 pencils","D 45 pencils"],"correct":["B"],"hint":"Multiply the number of pencils per student by the total number of students.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"A jar has 90 jelly beans. Three children share them equally. How many jelly beans does each child get?","options":["A 27 jelly beans","B 30 jelly beans","C 33 jelly beans","D 45 jelly beans"],"correct":["B"],"hint":"Divide the total number of jelly beans by the number of children.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"A runner jogged 4 miles each day for 6 days. Then she rested for 2 days and jogged 5 miles a day for 3 more days. How many miles did she jog in all?","options":["A 34 miles","B 36 miles","C 39 miles","D 44 miles"],"correct":["C"],"hint":"Calculate each part separately (4×6 and 5×3) then add them.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"A toy store has 9 shelves. Each shelf holds 8 toys. How many toys does the store have in all?","options":["A 56 toys","B 63 toys","C 72 toys","D 81 toys"],"correct":["C"],"hint":"Multiply the number of shelves by the number of toys on each shelf.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"Ethan had 48 coins. He spent some coins and now has 19 coins left. How many coins did Ethan spend?","options":["A 19 coins","B 25 coins","C 29 coins","D 38 coins"],"correct":["C"],"hint":"Subtract the remaining coins from the starting total.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"A school store sells pencils for $0.25 each. Elena buys 4 pencils. How much does she pay?","options":["A $0.50","B $0.75","C $1.00","D $1.25"],"correct":["C"],"hint":"Multiply the cost of one pencil by the number of pencils.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"Grace has 5 boxes of 9 crayons each and 3 extra crayons. How many crayons does Grace have in all?","options":["A 42 crayons","B 45 crayons","C 48 crayons","D 51 crayons"],"correct":["C"],"hint":"First find how many are in the boxes (5×9), then add the extra ones.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"The library received 200 new books. They placed 25 books on each shelf. How many shelves did they fill?","options":["A 6 shelves","B 7 shelves","C 8 shelves","D 9 shelves"],"correct":["C"],"hint":"Divide the total number of books by the number that fit on each shelf.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"At a picnic, there are 48 sandwiches. 7 friends each eat 3 sandwiches. How many sandwiches are left?","options":["A 21 sandwiches","B 24 sandwiches","C 27 sandwiches","D 30 sandwiches"],"correct":["C"],"hint":"Find how many sandwiches are eaten (7×3), then subtract from the total.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"A bus route takes 25 minutes. If the bus makes 4 trips, how many total minutes does it travel?","options":["A 80 minutes","B 90 minutes","C 100 minutes","D 120 minutes"],"correct":["C"],"hint":"Multiply the time per trip by the number of trips.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"A store sells candy bars for $2 each. Tyler buys 6 candy bars and pays with a $20 bill. How much change does Tyler receive?","options":["A $6","B $7","C $8","D $9"],"correct":["C"],"hint":"Find the total cost (2×6), then subtract from $20.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"There are 63 students signed up for after-school clubs. Each club has 9 students. How many clubs are there?","options":["A 5 clubs","B 6 clubs","C 7 clubs","D 8 clubs"],"correct":["C"],"hint":"Divide the total number of students by the number in each club.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"Zoe collects 12 shells on Monday, 18 on Tuesday, and 15 on Wednesday. She gives 20 shells to her brother. How many shells does she have left?","options":["A 20 shells","B 25 shells","C 30 shells","D 35 shells"],"correct":["B"],"hint":"Add all the shells collected, then subtract the ones given away.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"A box of donuts holds 12 donuts. If you have 5 boxes, how many donuts do you have?","options":["A 48 donuts","B 55 donuts","C 60 donuts","D 65 donuts"],"correct":["C"],"hint":"Multiply the number of boxes by the number of donuts in each box.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"Henry has 100 stickers. He gives 15 to each of his 4 friends. How many stickers does Henry have left?","options":["A 30 stickers","B 40 stickers","C 50 stickers","D 60 stickers"],"correct":["B"],"hint":"Find how many stickers are given away (15×4), then subtract from 100.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"A school has 180 students. 90 students play sports and 45 students are in band. How many students do neither?","options":["A 35 students","B 40 students","C 45 students","D 50 students"],"correct":["C"],"hint":"Add the students in sports and band, then subtract from the total.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"A farmer picks 7 baskets of berries. Each basket holds 24 berries. How many berries does the farmer pick in all?","options":["A 148 berries","B 156 berries","C 162 berries","D 168 berries"],"correct":["D"],"hint":"Multiply the number of baskets by the number of berries in each basket.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"Maya sold 8 paintings. Some sold for $12 and the rest for $9. She sold 3 paintings for $12 each. How much did Maya earn in all?","options":["A $80","B $81","C $82","D $90"],"correct":["B"],"hint":"Calculate earnings from $12 paintings (3×12) and $9 paintings (5×9), then add.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"There are 4 tables in a classroom. Each table has 6 students. One student is absent. How many students are present?","options":["A 20 students","B 21 students","C 22 students","D 23 students"],"correct":["D"],"hint":"Find the total students (4×6), then subtract the absent one.","active":True},
    {"subject":"Math","domain":"OA","category":"Word Problems","type":"single","text":"A roller coaster ride can hold 8 people. If 56 people want to ride, how many full groups will ride?","options":["A 5 groups","B 6 groups","C 7 groups","D 8 groups"],"correct":["C"],"hint":"Divide the total number of people by the number that fit in each group.","active":True},
]

print(f"Numeric questions: {len(numeric_questions)}")
print(f"Single questions: {len(single_questions)}")
print(f"Total: {len(numeric_questions) + len(single_questions)}")
print()

print("Uploading numeric Word Problems questions...")
for i in range(0, len(numeric_questions), 25):
    batch = numeric_questions[i:i+25]
    upload_batch(batch)

print("Uploading single-choice Word Problems questions...")
for i in range(0, len(single_questions), 25):
    batch = single_questions[i:i+25]
    upload_batch(batch)

print("Done!")
