"""
60 grade 4 reading data, line plots and graphs questions (MD).

ALREADY RUN -- these questions are live in Supabase. This file is kept as the
source of record for data that is already in the database.

There is no dry-run flag: running this uploads on sight, and running it again
would duplicate every question above for Jaden. Check the `questions` table
before re-running.
"""
import json, urllib.request, time

URL = "https://zvffmucghcrqackghhlf.supabase.co/rest/v1/questions"
KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2ZmZtdWNnaGNycWFja2doaGxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY3MjkyNTIsImV4cCI6MjA5MjMwNTI1Mn0.eJHX6LmInRdBd5nt9t_jBJwILGEQ6_SeN6ADorlsWic"

def upload_batch(batch):
    data = json.dumps(batch).encode()
    req = urllib.request.Request(URL, data=data, method='POST')
    req.add_header('Content-Type', 'application/json')
    req.add_header('apikey', KEY)
    req.add_header('Authorization', f'Bearer {KEY}')
    req.add_header('Prefer', 'return=minimal')
    try:
        with urllib.request.urlopen(req) as r:
            print(f"  Batch of {len(batch)}: HTTP {r.status}")
    except urllib.error.HTTPError as e:
        print(f"  ERROR {e.code}: {e.read().decode()}")
    time.sleep(0.3)

# 59 Data & Graphs questions (domain MD)
questions = [
    # --- SINGLE CHOICE ---
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A bar graph shows apples=8, bananas=5, grapes=10. Which fruit is most popular?","options":["A Apples","B Bananas","C Grapes","D They are the same"],"correct":["C"],"hint":"Grapes have the highest bar at 10.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A bar graph shows: cats=6, dogs=9, birds=3. How many more dogs than birds are there?","options":["A 3","B 6","C 9","D 12"],"correct":["B"],"hint":"9 - 3 = 6 more dogs than birds.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A pictograph uses smiley faces to show votes. Each smiley = 2 votes. If pizza shows 4 smileys, how many votes did pizza get?","options":["A 4","B 6","C 8","D 2"],"correct":["C"],"hint":"4 smileys × 2 votes each = 8 votes.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A tally chart shows: red=|||||, blue=|||, green=||||. Which color has the most tallies?","options":["A Red","B Blue","C Green","D Red and Green tied"],"correct":["A"],"hint":"Red has 5 tallies (|||||), which is the most.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A line plot shows the number of books read: x at 1, xxx at 2, xx at 3, x at 4. How many students read exactly 2 books?","options":["A 1","B 2","C 3","D 4"],"correct":["C"],"hint":"There are 3 x's above the number 2.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A bar graph shows: Monday=15, Tuesday=12, Wednesday=18, Thursday=10. On which day were the fewest items sold?","options":["A Monday","B Tuesday","C Wednesday","D Thursday"],"correct":["D"],"hint":"Thursday has the lowest bar at 10.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A pictograph shows stars collected: Ann=3 stars, Ben=5 stars, Cal=4 stars. Each star = 10. How many total?","options":["A 120","B 110","C 100","D 130"],"correct":["A"],"hint":"(3+5+4) × 10 = 12 × 10 = 120.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A bar graph shows favorite sports: soccer=14, basketball=11, baseball=8, swimming=13. How many students were surveyed?","options":["A 46","B 36","C 56","D 26"],"correct":["A"],"hint":"14+11+8+13 = 46 students total.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A tally chart shows: apples=7, oranges=4, bananas=6. How many more apples than oranges?","options":["A 2","B 3","C 4","D 1"],"correct":["B"],"hint":"7 - 4 = 3 more apples than oranges.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A line plot of plant heights (inches): one x at 3, two x at 4, four x at 5, one x at 6. What height appears most often?","options":["A 3 inches","B 4 inches","C 5 inches","D 6 inches"],"correct":["C"],"hint":"5 inches has four x's — the most.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A bar graph shows books read: Jan=20, Feb=15, Mar=25, Apr=10. How many more books were read in March than April?","options":["A 10","B 15","C 20","D 25"],"correct":["B"],"hint":"25 - 10 = 15 more books in March.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A pictograph uses stars where each star = 5. If soccer shows 6 stars, how many students chose soccer?","options":["A 6","B 11","C 30","D 25"],"correct":["C"],"hint":"6 stars × 5 = 30 students.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A tally chart for favorite colors: Red=|||| ||, Blue=||||, Green=||| . How many chose Blue?","options":["A 5","B 4","C 7","D 3"],"correct":["B"],"hint":"Blue = |||| = 4 tallies.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A line plot shows pencil lengths. Most marks are at 6 inches. What does this tell us?","options":["A Most pencils are longer than 6 inches","B 6 inches is the most common pencil length","C All pencils are 6 inches","D No pencils are 6 inches"],"correct":["B"],"hint":"The most marks on a line plot show the most common value.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A bar graph shows: tigers=8, lions=5, bears=8, wolves=3. Which animals are tied?","options":["A Lions and wolves","B Tigers and bears","C Bears and lions","D Wolves and tigers"],"correct":["B"],"hint":"Tigers=8 and bears=8. They are tied.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A pictograph shows cookies sold: Mon=2 cookies, Tue=4 cookies, Wed=3 cookies. Each cookie symbol = 10. How many were sold on Tuesday?","options":["A 4","B 20","C 40","D 30"],"correct":["C"],"hint":"4 cookie symbols × 10 = 40.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"Students recorded how many pets they have. Line plot: 0 pets: xxx, 1 pet: xxxxx, 2 pets: xx, 3 pets: x. How many students have 1 pet?","options":["A 2","B 3","C 5","D 1"],"correct":["C"],"hint":"There are 5 x's above the 1 on the line plot.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A bar graph shows school lunch choices: pizza=25, salad=10, sandwich=15, soup=12. What is the total?","options":["A 62","B 52","C 72","D 42"],"correct":["A"],"hint":"25+10+15+12 = 62 total.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A tally chart has 3 groups. Group A: 12 tallies, Group B: 7 tallies, Group C: 9 tallies. Which group has the least?","options":["A Group A","B Group B","C Group C","D Groups B and C are tied"],"correct":["B"],"hint":"Group B has only 7 tallies, the fewest.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A bar graph shows temperatures for 4 days (°F): Mon=65, Tue=72, Wed=68, Thu=75. On which day was it hottest?","options":["A Monday","B Tuesday","C Wednesday","D Thursday"],"correct":["D"],"hint":"Thursday has the highest bar at 75°F.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"In a pictograph, each apple symbol = 3. There are 5 apple symbols for 'Fuji' apples. How many Fuji apples are there?","options":["A 5","B 10","C 15","D 8"],"correct":["C"],"hint":"5 symbols × 3 = 15 Fuji apples.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A line plot shows distances students jumped (feet): 3, 3, 4, 4, 4, 5, 5, 6. What is the most common jump distance?","options":["A 3 feet","B 4 feet","C 5 feet","D 6 feet"],"correct":["B"],"hint":"4 appears three times — the most frequent.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A bar graph shows books in a library: fiction=120, non-fiction=80, poetry=45, biography=55. How many more fiction than non-fiction?","options":["A 30","B 40","C 50","D 60"],"correct":["B"],"hint":"120 - 80 = 40 more fiction books.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"Students voted for their favorite season. The tally shows: Spring=9, Summer=14, Fall=7, Winter=6. Which season got the fewest votes?","options":["A Spring","B Summer","C Fall","D Winter"],"correct":["D"],"hint":"Winter has only 6 votes, the fewest.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A bar graph shows visitors to a park: Week 1=45, Week 2=60, Week 3=55, Week 4=70. How many visitors total?","options":["A 220","B 230","C 210","D 240"],"correct":["B"],"hint":"45+60+55+70 = 230 visitors.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A pictograph shows raindrops for each day. Each raindrop = 2 inches of rain. Monday shows 3 raindrops. How much rain fell Monday?","options":["A 3 inches","B 5 inches","C 6 inches","D 2 inches"],"correct":["C"],"hint":"3 raindrops × 2 inches = 6 inches.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A line plot shows the ages of kids at a party: 7, 7, 8, 8, 8, 9, 10. How many kids are 8 years old?","options":["A 2","B 3","C 4","D 1"],"correct":["B"],"hint":"8 appears three times on the line plot.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A bar graph shows points scored per game: Game 1=23, Game 2=31, Game 3=18, Game 4=27. In which game were the fewest points scored?","options":["A Game 1","B Game 2","C Game 3","D Game 4"],"correct":["C"],"hint":"Game 3 has the lowest bar at 18 points.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A tally chart shows animals spotted on a hike: deer=||||, rabbit=|| |, squirrel=||. Which animal was spotted most?","options":["A Deer","B Rabbit","C Squirrel","D Deer and Rabbit tied"],"correct":["B"],"hint":"Rabbit has 3 tallies, deer has 4. Wait — deer=4, rabbit=3, squirrel=2. Deer spotted most.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A tally chart shows animals spotted: deer=||||, rabbit=|||, squirrel=||. How many animals total?","options":["A 7","B 8","C 9","D 10"],"correct":["C"],"hint":"4 + 3 + 2 = 9 animals total.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A bar graph of students' favorite subjects: math=18, science=14, reading=22, art=11. How many more students prefer reading than math?","options":["A 4","B 6","C 8","D 2"],"correct":["A"],"hint":"22 - 18 = 4 more students prefer reading.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"In a pictograph of ice cream flavors, chocolate has 7 scoops and vanilla has 4 scoops. Each scoop = 5. How many more people chose chocolate?","options":["A 3","B 10","C 15","D 35"],"correct":["C"],"hint":"(7-4) × 5 = 3 × 5 = 15 more people.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A line plot shows quiz scores: 7, 7, 8, 9, 9, 9, 10, 10. What is the highest score shown?","options":["A 7","B 8","C 9","D 10"],"correct":["D"],"hint":"The rightmost value on the line plot is the highest: 10.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A bar graph shows rainfall (inches): Jan=3, Feb=2, Mar=5, Apr=4. What is the total rainfall for all 4 months?","options":["A 12","B 14","C 16","D 10"],"correct":["B"],"hint":"3+2+5+4 = 14 inches total.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"Students recorded how many siblings they have: 0=||||, 1=|||| |, 2=|||, 3=|. How many students have 1 sibling?","options":["A 4","B 5","C 3","D 1"],"correct":["B"],"hint":"|||| | = 5 tallies for 1 sibling.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A pictograph shows goals scored. Each ball = 2 goals. Tim has 4 balls, Sara has 3 balls. How many total goals?","options":["A 7","B 12","C 14","D 8"],"correct":["C"],"hint":"(4+3) × 2 = 7 × 2 = 14 goals.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A line plot shows the number of pages read: 10=xx, 15=xxxx, 20=xxx, 25=x. How many students read 15 pages?","options":["A 1","B 2","C 3","D 4"],"correct":["D"],"hint":"There are 4 x's above 15.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A bar graph shows students in each class: Room 1=24, Room 2=28, Room 3=22, Room 4=26. Which room has the most students?","options":["A Room 1","B Room 2","C Room 3","D Room 4"],"correct":["B"],"hint":"Room 2 has the highest bar at 28 students.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A tally chart shows types of weather last month: sunny=18, cloudy=7, rainy=5. How many days total?","options":["A 28","B 30","C 25","D 20"],"correct":["B"],"hint":"18+7+5 = 30 days total.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A pictograph uses flower symbols, each = 4. Roses show 5 flowers, tulips show 3 flowers. How many more roses than tulips?","options":["A 2","B 4","C 6","D 8"],"correct":["D"],"hint":"(5-3) × 4 = 2 × 4 = 8 more roses.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A line plot shows shoe sizes of students: 3, 4, 4, 4, 5, 5, 6. What size is most common?","options":["A 3","B 4","C 5","D 6"],"correct":["B"],"hint":"Size 4 appears three times — the most.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A bar graph shows books sold each week. Week 3 bar reaches 45. Week 1 bar reaches 30. How many more books sold in Week 3?","options":["A 5","B 10","C 15","D 20"],"correct":["C"],"hint":"45 - 30 = 15 more books in Week 3.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A student surveys classmates about favorite lunch. Results: pizza=12, tacos=8, sandwiches=10, salad=5. What is the difference between the most and least popular?","options":["A 5","B 7","C 8","D 10"],"correct":["B"],"hint":"Most=pizza(12), least=salad(5). 12-5=7.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A pictograph shows stickers collected. Each star = 5 stickers. Ann=4 stars, Bob=2 stars. How many total stickers?","options":["A 6","B 20","C 30","D 10"],"correct":["C"],"hint":"(4+2) × 5 = 6 × 5 = 30 stickers.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A line plot shows number of pull-ups: 5=x, 6=xx, 7=xxxx, 8=xxx, 9=x. What is the range?","options":["A 4","B 3","C 5","D 2"],"correct":["A"],"hint":"Range = highest - lowest = 9 - 5 = 4.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A bar graph shows donations by class. Mr. Smith's class=45, Ms. Jones's class=52, Mrs. Lee's class=38. Which class donated most?","options":["A Mr. Smith's","B Ms. Jones's","C Mrs. Lee's","D All equal"],"correct":["B"],"hint":"Ms. Jones's class donated 52 — the most.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A tally chart shows how students get to school: bus=||||||||, walk=||||, car=|||| |. How many students walk?","options":["A 4","B 5","C 8","D 9"],"correct":["A"],"hint":"Walk = |||| = 4 tallies.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A pictograph shows points scored. Each star = 10 points. If Team A has 8 stars and Team B has 5 stars, how many more points does Team A have?","options":["A 3","B 13","C 30","D 80"],"correct":["C"],"hint":"(8-5) × 10 = 3 × 10 = 30 more points.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A line plot shows heights of plants (cm) in a science experiment. Which type of display is being used?","options":["A Bar graph","B Pictograph","C Tally chart","D Line plot"],"correct":["D"],"hint":"A line plot shows data along a number line with marks above each value.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A bar graph is scaled by 5. A bar reaches the 8th line. What value does it represent?","options":["A 8","B 30","C 40","D 45"],"correct":["C"],"hint":"8 lines × 5 = 40.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"In a class survey, 15 students chose dogs, 9 chose cats, 6 chose fish as favorite pets. How many more students chose dogs than cats?","options":["A 6","B 9","C 4","D 3"],"correct":["A"],"hint":"15 - 9 = 6 more students chose dogs.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A pictograph shows books read. Each book symbol = 3. Lisa=5 symbols, Mark=4 symbols, Anna=6 symbols. Who read the most?","options":["A Lisa","B Mark","C Anna","D Lisa and Anna tied"],"correct":["C"],"hint":"Anna has 6 symbols × 3 = 18 books — the most.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A tally chart shows favorite fruits of 24 students. If apple=10, banana=8, grape=6, how many students have not been counted?","options":["A 0","B 2","C 4","D 6"],"correct":["A"],"hint":"10+8+6 = 24. All students are counted.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A line plot shows the number of glasses of water kids drink: 3=xx, 4=xxxx, 5=xxx, 6=x. What is the total number of students?","options":["A 8","B 9","C 10","D 12"],"correct":["C"],"hint":"2+4+3+1 = 10 students total.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A bar graph shows the number of cars in a parking lot each hour. 9 AM=12, 10 AM=18, 11 AM=24, 12 PM=30. What pattern do you see?","options":["A Decreasing by 6 each hour","B Increasing by 6 each hour","C Staying the same","D Increasing by 12 each hour"],"correct":["B"],"hint":"12, 18, 24, 30 — increases by 6 each hour.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"Students voted for a field trip: zoo=14, museum=11, beach=19, park=16. What is the total number of votes?","options":["A 60","B 56","C 50","D 70"],"correct":["A"],"hint":"14+11+19+16 = 60 votes total.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A pictograph key says each symbol = 4. A row shows 3 full symbols and a half symbol. What is the total?","options":["A 12","B 14","C 16","D 3.5"],"correct":["B"],"hint":"3 × 4 = 12 plus half of 4 = 2. Total = 14.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A line plot shows test scores (out of 10). Scores: 6=x, 7=xxx, 8=xxxx, 9=xx, 10=x. How many students scored higher than 8?","options":["A 2","B 3","C 4","D 5"],"correct":["B"],"hint":"Scores above 8: 9=2 students, 10=1 student. Total = 3.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"A bar graph shows number of steps walked: Mon=3000, Tue=4500, Wed=6000, Thu=3500. On which day did the student walk 4500 steps?","options":["A Monday","B Tuesday","C Wednesday","D Thursday"],"correct":["B"],"hint":"Tuesday's bar reaches 4500.","active":True},
    {"subject":"Math","domain":"MD","category":"Data & Graphs","type":"single","text":"In a tally chart, Group A has 15 tallies and Group B has 9 tallies. How many more tallies does Group A have?","options":["A 5","B 6","C 7","D 9"],"correct":["B"],"hint":"15 - 9 = 6 more tallies for Group A.","active":True},
]

print(f"Total questions: {len(questions)}")
single_qs = [q for q in questions if q['type'] == 'single']
numeric_qs = [q for q in questions if q['type'] == 'numeric']
print(f"Single: {len(single_qs)}, Numeric: {len(numeric_qs)}")

total_uploaded = 0
for qs in [single_qs, numeric_qs]:
    for i in range(0, len(qs), 25):
        upload_batch(qs[i:i+25])
        total_uploaded += len(qs[i:i+25])

print(f"Done. Total uploaded: {total_uploaded}")
